### ISSUE TITLE
Add [CROSS OFF / UNDO] to G's caches

### ISSUE THREAD

**Issue by metoxys** [PLTytus/GTAWeb#11]
**Describe your idea:**
G's caches are very similar to stash houses in that there's one per day with a random location. Stash houses have a "cross off" option to easily hide them once you've collected them for the day. G's caches do not. Please add it for G's caches.

**Examples (if you was inspired by some other website or project):**
Functionality exists already for Stash houses

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
Makes life easier for me. Also "website" at the end of the prompt is misspelled

**Comment by PLTytus** [comment]
Done.
