### ISSUE TITLE
Can't cross off RC Bandito time trial because it's obscured by G's Cache

### ISSUE THREAD

**Issue by metoxys** [PLTytus/GTAWeb#12]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: Normal
- Subpage name: map (GTAO Los Santos)
- Supbage URL: https://gtaweb.eu/gtao-map/ls/2
- Setted language: English
- Device type: desktop
- Device: PC
- OS and its version: Win10x64
- Browser and its version chromium 78.0.3904.87

**Describe the issue (a clear and detailed description of the issue):**
I can't click on the RC Bandito Time Trial to cross it off because it is in the same location as a G's Cache, and that one takes priority on the click

**To Reproduce  (detailed steps to reproduce the behavior):**
1. Have RC Bandito Time Trials and G's Caches active on the map at the same time
2. Attempt to click on the RC Bandito Time Trial

**Expected behavior  (how it should work):**
The RC Bandito Time Trial is layered on top of G's Cache because it is a smaller icon

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
![image](https://github.com/PLTytus/GTAWeb/assets/6764458/87b6c4bc-db1e-48dd-800d-e5ec0d72fc1a)
![image](https://github.com/PLTytus/GTAWeb/assets/6764458/b6ae042e-de26-4f88-90b6-e72394f68e60)

**Additional context (if you have somthing more to add):**
-

**Comment by metoxys** [comment]
> The RC Bandito Time Trial is layered on top of G's Cache because it is a smaller icon

Another good solution would be to have crossed off markers layered on the bottom

**Comment by PLTytus** [comment]
> Another good solution would be to have crossed off markers layered on the bottom
z-index (layer level) is setted for whole groups of markers, lowering it for single marker would be pain in the ass...

I lowered z-index for groups with areas (such as G's Cahces, Gang Attacks, ...), should be enough to avoid this situations with only intermingling of the two areas remains problematic.
