### ISSUE TITLE
Weapon Locations

### ISSUE THREAD

**Issue by tittlse** [PLTytus/GTAWeb#13]
**Describe your idea:**
add markers for weapon locations that can be found in freemode

**Examples (if you was inspired by some other website or project):**
at one point i found a sniper rifle on or around mt. chiliad, so i thought there might be more weapons elsewhere on the map

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
...

**Comment by PLTytus** [comment]
I found some coordinates. I need test some of them to be sure there are accurate. I will add them without screenshots - maybe I will add them later - but there is between 650 and 800 locations. Probably part of them is only multiplayer and the rest only singleplayer.

**Comment by PLTytus** [comment]
Spawns in online (except parachutes) seems to be limited, so not all of found coordinates will be active:
```
    uVar0 = Global_262145.f_12179 /* Tunable: NUMBEROFWEAPONPICKUPS */ /* 40 */;
    iVar1 = Global_262145.f_12180 /* Tunable: PERCENTAGEOFGUNS */ /* 35 */;
    iVar2 = Global_262145.f_12181 /* Tunable: PERCENTAGEOFPROJECTILES */ /* 40 */;
    iVar3 = Global_262145.f_12182 /* Tunable: PERCENTAGEOFMELEE */ /* 20 */;
```

**Comment by PLTytus** [comment]
Singleplayer: https://gtaweb.eu/gtao-map/ls2/13f0kifpx2io
Multiplayer: https://gtaweb.eu/gtao-map/ls/1omfoz45j6mpi5j7e7gjil74lc
