### ISSUE TITLE
The falling icons ...

### ISSUE THREAD

**Issue by EncreTarte87377** [PLTytus/GTAWeb#14]
Please , can you stop with the falling icons , icons who fall like snow , today it's flags , poland flags i think , it's annoying , when you are dezoom , sometimes you can't see the other icons .. 
Maybe another way to give support for a cause you want to defend will be better ? 
The last one for easter was hiding some spots , on my computer sometimes it stop in motion , so it hide the in game map icons ... ^^ 
Thanks for your awesome work !

**Comment by PLTytus** [comment]
I was planning to add disable feature when I was adding this stuff. But I added it in rush and kind of forget about disable option :sweat_smile:

Here is an option:
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/cd0a38ae-0042-4939-a0bd-8c8311ec1b4f)
It sets cookie for 24 hours if you decide to disable it.

Also, if you hover your cursor above (or touch it on mobile) you will see info, what it is about:
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/de3787d7-cd0d-4585-a60f-fbba8048317d)

**Comment by EncreTarte87377** [comment]
Ok thanks , good idea to put a description of the celebration / for what is the falling icons , it help to better understand what is the celebration of the day ! 
Next time it happen , i will know how to disable it ! :D 
Thanks for your answer , and thanks again for this awesome interactive map , very helpful , i use it every day :D 
When i can , i will give you a donnation.
A last question : is there a mobile app of this map ? i searched but i found nothing , only one other "map" but not ineractive and with only a part of all the real content of the game ! ^^'

**Comment by PLTytus** [comment]
> is there a mobile app of this map ?

No. Mobile apps is a whole diffrent story ;) However you can add website to Home Screen and it works kind of mobile app. Ther are multiple manifest files, so you can add toolkit and map as separate "apps":

![image](https://github.com/PLTytus/GTAWeb/assets/34415908/b40a54b9-cf04-432b-bcce-82c5a2eeb610)

**Comment by EncreTarte87377** [comment]
Oh ok , yes but i already saved the map link in my mobile web browser's home page , so it's almost the same ^^ 
Yes it work but it's not perfect like a mobile app without the restrictions of the browser , like zoom , some bugs with icons , etc ... 
Just for my curiosity , why it's a whole different story ? It's so different as a website map ? Or a way more complicated ? or too expansive maybe ?
Because i'm sure you can have a lot of users with a mobile app on android and iOS , the first reflex of a big part of the players when they start a gta is searching a map on the play store , and a lot stop their search at this point because they are not confortable with a mobile web browser , and see a lot of console players don't have a PC , only a smartphone or a tablet ! 
I already see / noticed it on FB groups about GTA , when i share your website , a lot of people discover it for the first time , and some always ask if it's possible to use it on a smartphone ... a good clue about the amount of people who can become a user of this kind of map app ! 
For the next GTA, the VI , the first who will do a interactive map app rich of content like your map will earn a lot ^^'  
I know nothing about app dev and website dev , etc , so i ask ^^
