### ISSUE TITLE
Add Cross Off option for time trials

### ISSUE THREAD

**Issue by metoxys** [PLTytus/GTAWeb#16]
**Describe your idea:**
See title, might also apply for HSW time trials

**Examples (if you was inspired by some other website or project):**
Other content that rotates over time and can be crossed off, like UFO sightings

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
-

**Comment by PLTytus** [comment]
I am not sure how those two resets and I think it was changed a few times. You can complete those two each day to receive full reward or just once per week? If it is daily, then I can update it quickly - if it is weekly I will probably need to make more changes.

**Comment by metoxys** [comment]
RC Bandito & Junk Energy - daily  
Time Trial & HSW Time Trial - weekly

**Comment by PLTytus** [comment]
Done. It is connected to tunable EVENT_WKLY from CD_GLOBAL pool.
