### ISSUE TITLE
Vending machines (e-Cola and Sprunk)

### ISSUE THREAD

**Issue by ther4ven** [PLTytus/GTAWeb#19]
**Describe your idea:**
Hi.
I'd like to see vending machines on the map (e-Cola and Sprunk), which ones are indoors and outdoors.

**Examples (just like in this image):**
[Imgur - GTA5 Map](https://i.imgur.com/ZsXTQha.jpeg)

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
Thank you for this website, really useful!!!

**Comment by PLTytus** [comment]
eCola: https://gtaweb.eu/gtao-map/ls/4xdkkfek4xs
Sprunk: https://gtaweb.eu/gtao-map/ls/9ur54ut49vk
For singleplayer should be the same:
eCola: https://gtaweb.eu/gtao-map/ls2/13f0kjf8h3i8
Sprunk: https://gtaweb.eu/gtao-map/ls2/26u152ugy70g
