### ISSUE TITLE
Low-contrast icons

### ISSUE THREAD

**Issue by danield72** [PLTytus/GTAWeb#2]
**Use icons with higher contrast:**
...

**Dark purple street dealer icons (speech bubble) are difficult to locate on a black background...use a brighter color**
...

**Comment by PLTytus** [comment]
Old one:
![](https://github.com/PLTytus/GTAWeb/assets/34415908/d003c2f6-523c-41fa-b5d5-eff26df52c32)

New one:
![](https://github.com/PLTytus/GTAWeb/assets/34415908/c44ac5d1-3e03-46fa-8c0d-72e21703088a)

I forced clearing cache for that one, by old my be still cached for you.

**Comment by danield72** [comment]
This makes a huge difference, thank you very much
