### ISSUE TITLE
Cant move marker one mobile devices

### ISSUE THREAD

**Issue by dahein** [PLTytus/GTAWeb#20]
- Priority:  Low
- Subpage name: map
- Supbage URL: https://gtaweb.eu/gtao-map/ls/2
- Setted language: English
- Device type: mobile
- Device: Samsung S20
- OS and its version:  Android 13
- Browser and its version: Chrome 114.0.5735.196

Describe the issue:

After selecting acid Lab sell missions, I cannot move the marker on mobile devices

**To Reproduce  (detailed steps to reproduce the behavior):**

1. Select acid Lab sell missions
2. Select yellow marker
3. Try to move (not working)

**Expected behavior  (how it should work):**

Holding yellow marker and moving it or holding green circle and moving it

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
...

**Additional context (if you have somthing more to add):**

Maybe there is only an explanation missing on how this works

**Comment by PLTytus** [comment]
I am aware ot this issue on mobile devices - at this moment draggable markers does not work on mobile. I'll let you know if i figure it out.

**Comment by PLTytus** [comment]
Looks like it is Leaflet library issue, it works when switching version to 1.6.0 (current is 1.9.4) but some other features are broken on this older version. I am afraid, only think I can do is wait for fixes in future versions of this library.

**Comment by PLTytus** [comment]
I found workaround for current version of Leaflet library, All draggable markers features should now work on desktop and mobile.
