### ISSUE TITLE
The key is in the hints in the Daily Objectives menu

### ISSUE THREAD

**Issue by Mykytius** [PLTytus/GTAWeb#21]
- Priority: Low
- Subpage name: Daily Objectives
- Supbage URL: https://gtaweb.eu/gtao-toolkit
- Setted language: All
- Device type: desktop
- Device: All desktop
- OS and its version: All desktop (tested on: Windows 11)
- Browser and its version: All (tested on: Google Chrome 117.0.5938.89, Microsoft Edge 117.0.2045.31)

**Describe the issue:**
If you open the Daily Objectives selection menu, a key (I don't know what to call it) will be displayed on the objectives that have hints.
(https://imgur.com/a/LZe1RqY)

When the Daily Objectives menu is closed, the tooltip is displayed correctly.
(https://imgur.com/a/nj59UE7)

**To Reproduce:**
1. Open the "Toolkit" tab"
2. Add "Daily Objectives"
3. Open the daily objectives selection menu
4. Move the cursor to a daily objective that has a tooltip

**Expected behavior:**
Do not display the key

**Screenshots or video:**
1. https://imgur.com/a/LZe1RqY
2. https://imgur.com/a/nj59UE7

**Comment by PLTytus** [comment]
Hints should not be displayed in selection menu, should be displayed only for already selected objective (if it has a hint).
I do not remember why I decide it should be this way - probably tooltips was bugged on Firefox :sweat_smile:
But i forgot to remove title attribute for options in selection menu, thats why it was displayed.
Anyway - it is fixed now.
