### ISSUE TITLE
Almost all parachute positions.

### ISSUE THREAD

**Issue by Mykytius** [PLTytus/GTAWeb#22]
**Location:**
Almost all parachute positions. All screenshots of parachute locations on the map are sorted along with screenshots in the archive.

**What is wrong with current screenshot:**
missing

**Your screenshot:**
https://drive.google.com/file/d/1jl6JF0rb2h_8VNYq53AtdPw8We-KwJEt/view?usp=sharing

**Comment by PLTytus** [comment]
Added and I photographed the rest of them - also the singleplayer ones. [Some locations are funny.](https://twitter.com/PLTytus/status/1704597126569697451)

**Comment by Mykytius** [comment]
Thanks for adding screenshots to the map, but not all are there now. Some places that I definitely remember taking pictures of don't have screenshots on the map.

**Comment by PLTytus** [comment]
Cloudflare cached the placeholders. I refreshed the cache - should be  accessible now.
