### ISSUE TITLE
Browser Update extension is bogus

### ISSUE THREAD

**Issue by WhiteCat-GB** [PLTytus/GTAWeb#23]
Hey there!
Love and use your website daily!
I've noticed today a pop-up claiming I should update my browser. After a small background check, you may want to remove that banner.

https://www.enigmasoftware.com/updatebrowserorg-removal/#:~:text=If%20computer%20users%20click%20on,installed%20on%20the%20affected%20computer. 

Information here ^^

Thanks and keep up the good work!

**Comment by PLTytus** [comment]
Website usese browser-update.org not update-browser.org
Which browser do you use? Name and version.
The website you shared looks like a scam.
You might saw not the actaul browser update pop up but some advertisement, best provide a screenshot (you can copy-paste image directly to the editor on GitHub)

**Comment by WhiteCat-GB** [comment]
![image](https://github.com/PLTytus/GTAWeb/assets/71231538/bd434502-646e-41af-83dd-d72643706304)

**Comment by PLTytus** [comment]
Provided link on the website is valid link to Google Chrome update.
Update the browser, the newest version is 119. If still do not trust this URL you can update Chrome by going to settings of hte browser.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/e1312efa-5835-4955-a02a-f7f5d0868021)

**Comment by WhiteCat-GB** [comment]
Appreciate the information. Can never be too careful. Sorry for bothering
you.
