### ISSUE TITLE
Icon not clearly distinctive on map

### ISSUE THREAD

**Issue by dod1k228** [PLTytus/GTAWeb#26]
Hello

Using interactive map for acid lab delivery missions
Icon of paperboy is very small and it is easy to miss it on map
Is it possible to change the icon or at least make outline/change color ?

**Comment by PLTytus** [comment]
I made some changes for this icon, let me know if it is more visible to you now.

**Comment by dod1k228** [comment]
thank you thank you!!
it is much better now
