### ISSUE TITLE
Bad pictures on bunker

### ISSUE THREAD

**Issue by Modz-Br34k3rS** [PLTytus/GTAWeb#27]
Some images of the bunker are not the right ones.

Here in screenshot, that of Lago Zancudo which displays the image of the Raton Canyon.
The image of the Raton Canyon is that of Paleto, the image of Paleto is that of Chumash... Some reversals! ;)

![image](https://github.com/PLTytus/GTAWeb/assets/149151791/d4619d45-ee1d-4552-903f-f92943c5ccc5)

Modz-Br34k3rS

**Comment by PLTytus** [comment]
Fixed. Thanks.
