### ISSUE TITLE
UFO

### ISSUE THREAD

**Issue by Mykytius** [PLTytus/GTAWeb#28]
**Location:** Shown in screenshots
...

**What is wrong with current screenshot:** My is better
...

**Your screenshot:** https://drive.google.com/file/d/1wsQIpr3V-c2Po_SDu44EnDbVeQQ2WkF3/view?usp=sharing
...

**Comment by PLTytus** [comment]
I've added screenshots for all locations (including ones you did not share). From you, I used only one screenshoot, the rest of them are from me and anonymous sources.
Anyway, thanks for sharing, I had a lot to choose from ;)
