### ISSUE TITLE
Timer - Lucky Wheel

### ISSUE THREAD

**Issue by Stroobboob** [PLTytus/GTAWeb#29]
A timer for the one a day spin of the wheel in the casino

**Comment by PLTytus** [comment]
Added to [toolkit](https://gtaweb.eu/gtao-toolkit). You can also turn on notification for all of this countdowns.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/38b6ca32-60ba-4851-a336-bb32cb23341e)
