### ISSUE TITLE
combine gta online account with GTAWep.eu for clarity with what you have (example: the amount of crates you have)

### ISSUE THREAD

**Issue by PrisesTurbo** [PLTytus/GTAWeb#33]
**Describe your idea:**
add a button to see what you have in online

**Examples (if you was inspired by some other website or project):**
...

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
...

**Comment by PLTytus** [comment]
Duplicate of https://github.com/PLTytus/GTAWeb/issues/6
For the amount of crates, you can use [https://gtaweb.eu/gtao-toolkit](toolkit)
