### ISSUE TITLE
Bunker product

### ISSUE THREAD

**Issue by SpydaLog** [PLTytus/GTAWeb#34]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: I don't know]
- Subpage name: Toolkit
- Supbage URL: https://gtaweb.eu/gtao-map/ls/2]](https://gtaweb.eu/gtao-toolkit)
- Setted language: English
- Device type: Laptop
- Device: Acer
- OS and its version: Windows 11
- Browser and its version: Chrome - Version 120.0.6099.71 (Official Build) (64-bit)

The totals for products for both normal and distance are showing exactly the same amount instead of 2 different amounts like every other type of product listed
...

**To Reproduce  (detailed steps to reproduce the behavior):**
1. ...
2. ...
3. ...

**Expected behavior  (how it should work):**
...

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
...

**Additional context (if you have somthing more to add):**
...

**Comment by PLTytus** [comment]
Fixed. The problem occurred only when the GTA+ option was checked.

**Comment by SpydaLog** [comment]
Hi! Sorry if this reopens but is this still expected to occur when gta+
option is selected as still encounteringm  myself?

Works fine if turn gta+ option off

**Comment by PLTytus** [comment]
Works for me. If simple refresh does not help, refresh website using CTRL+F5 combination.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/ace5dda6-2593-427d-8312-e225d23f7def)

**Comment by SpydaLog** [comment]
Thanks

Very odd

Tried in both chrome & edge last night and never used in edge, had same
issue

Just done hard refresh in chrome & now fixed
