### ISSUE TITLE
Wrong prices/premium products on Street Dealers

### ISSUE THREAD

**Issue by xgalto** [PLTytus/GTAWeb#35]
- Priority: [Low]
- Subpage name: [map]
- Supbage URL: [[e.g. https://gtaweb.eu/gtao-map/ls/2](https://gtaweb.eu/gtao-map/ls/25ru2zpfjryb8kz9qa)]
- Setted language: [English]
- Device type: [desktop]
- Device: [PC]
- OS and its version: [Windows 11]
- Browser and its version Chrome]

**Describe the issue (a clear and detailed description of the issue):**
Since the Chop Shop update (I think) the street dealers on the map does not match what's in game. For example the prices are incorrect and the premium product for each dealer is incorrect

**To Reproduce  (detailed steps to reproduce the behavior):**
1. Go to a steet dealer in game
2. Compare products the street dealer wants to buy with what's on the map

**Expected behavior  (how it should work):**
Should match

**Comment by PLTytus** [comment]
Should be ok now.
