### ISSUE TITLE
Motorcycle club safe infinite notification

### ISSUE THREAD

**Issue by beto580** [PLTytus/GTAWeb#36]
**Basic info:**
- Priority: High
- Subpage name: toolkit
- Subpage URL: https://gtaweb.eu/gtao-map/ls/2]](https://gtaweb.eu/gtao-toolkit
- Setted language: English
- Device type: desktop
- Device: PC
- OS and its version: Windows 11
- Browser and its version Microsoft Edge Version 120.0.2210.77 (Official build) (64-bit)

**Describe the issue (a clear and detailed description of the issue):**
The notification for the motorcycle club safe triggers continuously after the supplies deplete

**To Reproduce  (detailed steps to reproduce the behavior):**
1. Mark the motorcycle club safe as owned and showing
2. Hit Resupply
3. Once the supplies run out you get the notification infinitely and the only way to make it stop is to disable this particular safe.

**Expected behavior  (how it should work):**
... The notification should only appear once. This is the only safe with this erratic notification

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
...
![image](https://github.com/PLTytus/GTAWeb/assets/12603761/5cc8013a-b549-4bc9-b0a4-d91a229caa20)
![image](https://github.com/PLTytus/GTAWeb/assets/12603761/10d5a6db-7f07-4dee-9ed6-c1e7a6d97ffb)
![image](https://github.com/PLTytus/GTAWeb/assets/12603761/895d322e-40bb-4fdf-adf6-e1831d953d0f)

**Additional context **
... As I said before, this is the only safe with these multiple notifications, is extremely annoying since it sounds and pop ups in the notification center many times continuosly

**Comment by PLTytus** [comment]
Fixed.
