### ISSUE TITLE
Popularity - salvage yard

### ISSUE THREAD

**Issue by SpydaLog** [PLTytus/GTAWeb#37]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: [in your opinion:  I don't know
- Subpage name: toolkit
- Supbage URL: https://gtaweb.eu/gtao-toolkit
- Setted language: English
- Device type: desktop
- Device: Laptop
- OS and its version: Windows 11
- Browser and its version Version 120.0.6099.129 (Official Build) (64-bit)

**Describe the issue (a clear and detailed description of the issue):**
The popularity seemingly decreases whether online or not for salvage yard and due to this the safe amount is not reflecting safe in game, could this be looked into and also possibly a reset button in case accidentally increase this bar by selecting tow truck or robbery, thank you

**To Reproduce  (detailed steps to reproduce the behavior):**
N/A

**Expected behavior  (how it should work):**
... Not stop counting down when offline as game seems to decrease popularity when offline

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
... N/A

**Additional context (if you have somthing more to add):**
... N/A

**Comment by PLTytus** [comment]
> also possibly a reset button in case accidentally increase this bar by selecting tow truck or robbery

Added +/- buttons, increase/decrease step is setted to 5%.

---

> The popularity seemingly decreases whether online or not

I think popularity goes off only while online, I will try to look into this, I will keep this issue open until confirmed.

**Comment by SpydaLog** [comment]
I think may have worded my report badly, meant in gta online popularity
decreases whether online or not, not your website which freezes the
popularity bar at whatever was at when click offline for toolbox. Yesterday
when I was online the toolbox showed popularity at like 80 percent but in
game seemingly 0% as was only accruing 300 each time in vault

**Comment by PLTytus** [comment]
Yeah, I was referencing to game. I will try to find answer in decompiled code or in the game itself. I can only say that basis on my play I was always getting max but I was grinding tow truck for achievements. I had 100% yesterday and did not play today. After 16 hours it should be at 0, so I will check it later today or tomorrow.

**Comment by PLTytus** [comment]
I just get 24k income, and I was offline more than 16 hours. Some saving issue maybe.
