### ISSUE TITLE
Wydarzenie Świąteczne z Bałwanami 

### ISSUE THREAD

**Issue by MasnyBenio** [PLTytus/GTAWeb#38]
Lokalizacja bałwana na mirror parku się nie zgadza

**Comment by PLTytus** [comment]
Zgadza się.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/d9510755-46b9-41d9-8fae-81fc34742cde)

**Comment by PLTytus** [comment]
Ta druga z parku też.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/1de1c124-99f3-4b7e-83ac-58a6e533c136)

**Comment by MasnyBenio** [comment]
U mnie go nie ma a tylko właśnie tu został  
  Dnia 25 grudnia 2023 01:18 PLTytus   napisał(a):  
 Ta druga z parku też.  
 github.com image.png (view on web)

**Comment by MasnyBenio** [comment]
Czy jest możliwość że może być gdzieś indziej  
  Dnia 25 grudnia 2023 01:18 PLTytus   napisał(a):  
 Ta druga z parku też.  
 github.com image.png (view on web)

**Comment by PLTytus** [comment]
Może pominąłeś inne miejsce, albo jakiś błąd, odpal sobie weryfikację plików gry najlepiej.

**Comment by MasnyBenio** [comment]
Gram na PlayStation  
  Dnia 25 grudnia 2023 09:59 PLTytus   napisał(a):  
 Może pominąłeś inne miejsce, albo jakiś błąd, odpal sobie weryfikację plików gry najlepiej.

**Comment by PLTytus** [comment]
Jeśli jesteś pewny że to tej lokacji brakuje, i reset gry / zmiana sesji nie pomaga to nie wiem, ale lokacje na mapie są poprawne.

**Comment by MasnyBenio** [comment]
Jak wykonać reset gry?? 
  Dnia 25 grudnia 2023 10:07 PLTytus   napisał(a):  
 Jeśli jesteś pewny że to tej lokacji brakuje, i reset gry / zmiana sesji nie pomaga to nie wiem, ale lokacje na mapie są poprawne.
