### ISSUE TITLE
Wrong Stats on Street Dealers

### ISSUE THREAD

**Issue by ThomasGW120** [PLTytus/GTAWeb#39]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: Normal
- Subpage name: GTAO Map
- Supbage URL: https://gtaweb.eu/gtao-map/ls/hio94mrrlk3m
- Setted language: English
- Device type: Desktop
- Device: PC
- OS and its version: Windows 10 Home
- Browser and its version: Chrome 120.0.6099.199

**Describe the issue (a clear and detailed description of the issue):**
The selling prices of street dealers are wrong

**Comment by PLTytus** [comment]
I believe, since December 2023 it may depend on session host. Try changing session, or create friends/crew/invite only.

**Comment by PLTytus** [comment]
Continuation of https://github.com/PLTytus/GTAWeb/issues/35

**Comment by PLTytus** [comment]
Can you confirm, this is still an issue? I was checking prices few times on session which exists basicly 24/7, and I had correct values.

**Comment by PLTytus** [comment]
I think, it is ok, now. But even if it is not, it looks like it is game issue, not much I could do - so, I am closing this for now, but I will back to this after next title update.
