### ISSUE TITLE
Download Map

### ISSUE THREAD

**Issue by Little-Night-Wolf** [PLTytus/GTAWeb#4]
**Describe your idea:**
I suggest to add a button for download a image with the map with the markers for share the location to friends, and can have a logo in the right back border for people know that the web from were it comes is gtaweb

**Examples (if you was inspired by some other website or project):**
For example to share with a friend the map with all related with cayo perico for help her

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
Will help people to share the information of the newest location of all related with dlc with friends and people around the world

**Comment by Qrix** [comment]
Already you can add custom markers and share it with friends by copying URL
![image](https://github.com/PLTytus/GTAWeb/assets/1106898/68723917-0092-4726-92f6-c032f32fb670)

**Comment by PLTytus** [comment]
As above, you can copy url to share something specifi, e.g. https://gtaweb.eu/gtao-map/ls/-/stunt-jumps
You can even share specific spot, by click "SHARE" in tooltip for selected content, e.g. https://gtaweb.eu/gtao-map/ls/-/stunt-jumps - the shared location is blinking.
I do not see a point in doing picture of the map. Besides, you can simply take a screenshot with logo visible or even add logo manually. The screenshot is also rather small, on the website you can zoom in.
Linking is also better for website popularity, it makes it visible higher for web search engines, such as Google.
