### ISSUE TITLE
Chop Peyote

### ISSUE THREAD

**Issue by LordByronRS** [PLTytus/GTAWeb#40]
**Describe your idea:**
Basically add additional info to the text of the Chop Peyote (https://gtaweb.eu/gtao-map/ls/-/peyote-plants-land/sm=51).

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
At the moment it says "There is a very good chance that after eating this peyote, you will turn into Chop - Franklin's dog."
This is not that accurate, because if you want to respawn as Chop, you need to have the singleplayer mission "Chop" completed.

**Comment by PLTytus** [comment]
Changed to "If you have completed the main story mission <i>Chop</i> in singleplayer, there is a very good chance that after eating this peyote, you will turn into Chop - Franklin's dog."
