### ISSUE TITLE
Vehicle locations

### ISSUE THREAD

**Issue by Jo-Saiyan** [PLTytus/GTAWeb#42]
You should add the vehicles and the spawn locations where they spawn.

**Comment by PLTytus** [comment]
Duplicate of https://github.com/PLTytus/GTAWeb/issues/10

**Comment by Jo-Saiyan** [comment]
On the cayo perico islandOn Jan 18, 2024, at 05:28, PLTytus ***@***.***> wrote:﻿
Closed #42 as completed.

**Comment by PLTytus** [comment]
Then, it is duplicate of https://github.com/PLTytus/GTAWeb/issues/31
