### ISSUE TITLE
police station info

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#43]
pd names:
> 
![map](https://github.com/PLTytus/GTAWeb/assets/160082047/bf79608a-7d09-4d1a-8bb7-2e44b44a416d)

snap sample:
![Paleto Bay](https://github.com/PLTytus/GTAWeb/assets/160082047/b233662e-b820-464d-92a8-8642942ab101)

screenshots in archive: 
[pd.zip](https://github.com/PLTytus/GTAWeb/files/14289814/pd.zip)

...

...

**Author:
...
leave it blank, don't have preferred nickname currently (and don't want github nickname to be displayed)

**Comment by haasinc42** [comment]
Rockford pd used wrong image, i will reupload another set in daylight

**Comment by haasinc42** [comment]
[snaps.zip](https://github.com/PLTytus/GTAWeb/files/14290404/snaps.zip)
pd snaps in daytime (rockford pd fixed )

**Comment by PLTytus** [comment]
Done. Thank you.
