### ISSUE TITLE
fire station and hospital screenshots

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#44]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
...
screenshots in one zip:
[fire and hospital.zip](https://github.com/PLTytus/GTAWeb/files/14328927/fire.and.hospital.zip)

took some screenshots of the fire stations and hospitals

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
...
missing

**Your screenshot (best copy-paste it here):**
...
sample fire station

![davis](https://github.com/PLTytus/GTAWeb/assets/160082047/40a86b19-864e-439c-9d49-babd1644949a)

sample hospital 

![st fiacre](https://github.com/PLTytus/GTAWeb/assets/160082047/9bfc8a46-be15-4c78-8b6d-966fa8a3ea2b)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
...
leave it blank

**Comment by PLTytus** [comment]
Done.
