### ISSUE TITLE
GTAO Toolkit - Bunker - posibility to hide research

### ISSUE THREAD

**Issue by jacklul** [PLTytus/GTAWeb#45]
A switch to mark all bunker research projects as completed could be nice (and hide its bar on the widget) - saves some pixels of width when organizing.

**Comment by PLTytus** [comment]
I do not understand, could you explain this further.

**Comment by jacklul** [comment]
What I mean is to add a switch that hides the research bar.

So that this: https://i.imgur.com/P8KeK1h.jpeg
Changes to this: https://i.imgur.com/OgI49hE.jpeg

**Comment by PLTytus** [comment]
Done.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/0882adc0-6a60-4e1a-8fdb-cf7e6ebcaf12)
