### ISSUE TITLE
Movie and Knife Flight screenshots

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#46]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
...
[knife flight.zip](https://github.com/PLTytus/GTAWeb/files/14344512/knife.flight.zip)
[movie.zip](https://github.com/PLTytus/GTAWeb/files/14344513/movie.zip)

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
...missing

**Your screenshot (best copy-paste it here):**
...
knife sample
![4  rockford hills](https://github.com/PLTytus/GTAWeb/assets/160082047/cef11bd0-925d-49c6-a034-1fdc4ff2a27b)

movie sample
![cinema doppler](https://github.com/PLTytus/GTAWeb/assets/160082047/2a985a88-8c00-4205-8efc-4e2013574670)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
...horseshoecrab34

**Comment by PLTytus** [comment]
> Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):
> ...horseshoecrab34

Do you want me to add this to the previous ones (https://github.com/PLTytus/GTAWeb/issues/43, https://github.com/PLTytus/GTAWeb/issues/44)?

**Comment by haasinc42** [comment]
sounds good, please add it 😊

**Comment by PLTytus** [comment]
✅ Added watermarks to https://github.com/PLTytus/GTAWeb/issues/43 and https://github.com/PLTytus/GTAWeb/issues/44.

**Comment by PLTytus** [comment]
✅ _Ten Cent Theater_ and _Tivoli Cinema_ added.
🔴 The _Doppler Cinema_ is property possible to buy in single player but movies cannot be seen there. The map shows location of _Oriental Theater_, which is next to _Doppler_. For now, I left "PICTURE NEEDED" placeholder at this location.

**Comment by haasinc42** [comment]
![Oriental Theater](https://github.com/PLTytus/GTAWeb/assets/160082047/4677d17c-2320-4f90-a078-32b57a3aac24)

[Oriental Theater.zip](https://github.com/PLTytus/GTAWeb/files/14375158/Oriental.Theater.zip)

**Comment by PLTytus** [comment]
✅ _Oriental Theater_ added.

**Comment by PLTytus** [comment]
✅ Knife flights added.
