### ISSUE TITLE
metro station screenshots

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#47]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
...
[metro station.zip](https://github.com/PLTytus/GTAWeb/files/14396033/metro.station.zip)

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
...
missing

**Your screenshot (best copy-paste it here):**
...
sample 
![portola drive](https://github.com/PLTytus/GTAWeb/assets/160082047/24f612fe-e2e3-45a6-b6b3-913109ed625d)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
...
horseshoecrab34

**Comment by PLTytus** [comment]
Added.
