### ISSUE TITLE
gas station screenshots / one location missing on map

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#48]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
...
screenshot zip
[gas station.zip](https://github.com/PLTytus/GTAWeb/files/14433677/gas.station.zip)

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
...
missing. and gas station at Harmony have not been marked

**Your screenshot (best copy-paste it here):**
...
map sample
![map](https://github.com/PLTytus/GTAWeb/assets/160082047/bd300b6c-2734-4b70-af9a-14143cdfa71e)

screenshot sample
![16  zancudo ron](https://github.com/PLTytus/GTAWeb/assets/160082047/d25a9e08-04e8-45cb-a886-b8238806d071)

Harmony gas station
![harmony gas](https://github.com/PLTytus/GTAWeb/assets/160082047/c85863af-d2d0-4eaf-81a6-32209740518d)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
...
horseshoecrab34

**Comment by PLTytus** [comment]
TODO:
- [ ] add missing location
- [ ] add screenshots

**Comment by PLTytus** [comment]
All done.
