### ISSUE TITLE
Set spawn time for Hens (EE)

### ISSUE THREAD

**Issue by elcuacua** [PLTytus/GTAWeb#50]
Set hours for when Hens spawn because they don't spawn at night.

Other animals like certain dog breeds have spawn times, and disappear off the map until the time comes.

**Comment by PLTytus** [comment]
There spawnd points for Hens which are active:
- only at Midnight
- all day long
- 7-18
- 7-19
- 15-22
Yoy can use [singleplayer map](https://gtaweb.eu/gtav-map/ls/-/spawn-animal-hen) to check all possible locations despite the spawn time.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/098490d0-52b5-49fb-ae05-31903f9edd38)
