### ISSUE TITLE
The pictures of where the items are

### ISSUE THREAD

**Issue by DemonSack** [PLTytus/GTAWeb#51]
I just don’t understand why the pictures y’all put on there to show you were like a treasure chest on the cayo map are always night time make it really hard to see them And also the 10 hidden Caches The change every day could really have a better Way of showing you where it is. Matter fact I’ll just sit and put no pictures of where anything is when it’s night time

**Comment by PLTytus** [comment]
That is why there is [this template](https://github.com/PLTytus/GTAWeb/issues/new?assignees=&labels=screenshot&projects=&template=screenshot.md&title=). If you have a better screenshot, open ticket with it, I will replace it on website as [others](https://github.com/PLTytus/GTAWeb/issues?q=is%3Aissue+label%3Ascreenshot+).
