### ISSUE TITLE
Sandy Shores Airfield gas station screenshot (missing location)

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#52]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
...
Sandy Shores Airfield

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
...
missing 

**Your screenshot (best copy-paste it here):**
...
![20240324175417_1](https://github.com/PLTytus/GTAWeb/assets/160082047/12f2ead1-df08-4f06-a348-de93e4bd8317)

[Sandy Shores.zip](https://github.com/PLTytus/GTAWeb/files/14743492/Sandy.Shores.zip)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
...
horseshoecrab34

**Comment by PLTytus** [comment]
[Added](https://gtaweb.eu/gtao-map/ls/-/gas-stations/sm=25)
