### ISSUE TITLE
Bookmarks redirecting to GTA VI page

### ISSUE THREAD

**Issue by alzbookstore** [PLTytus/GTAWeb#53]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: Normal
- Subpage name: Map?
- Supbage URL: https://gtaweb.eu/gtao-map/ls/hio94mrrlk3m
- Setted language: English
- Device type: iPad
- Device: iPad Pro, 12.9” (2021)
- OS and its version: iPadOS 17.5
- Browser and its version: Safari (iPadOS 17.5)

**Describe the issue (a clear and detailed description of the issue):**
Saving the current page option selection as a bookmark typically saves as a detailed bookmark that re-opens the same page with the same sidebar options selected (Street Dealers, Gun Van, etc).
Now loading any saved configuration of the page always redirects to the default for GTA 6: https://gtaweb.eu/gtavi-map/vc/0

**To Reproduce  (detailed steps to reproduce the behavior):**
1. Open https://gtaweb.eu/
2. Tap GTAO Map (or GTA V)
3. Observe page redirects to GTA VI instead
4. Manually select GTAO Map in upper right dropdown
5. Select desired markers for map
6. Save bookmark to Favorites
7. Close tab, open new tab
8. Tap Saved GTAO Map page
9. Observe loading GTA VI page

**Expected behavior  (how it should work):**
Typically this has worked flawlessly in the past. Tapping the saved bookmark reloads GTAO Map with the desired map markers.

This reproduced at least 6 times and now that I’ve tried again to get a screenshot it may have resolved? After having written the report…
Leaving issue open in case it serves to troubleshoot/correlate other reports.

**Comment by PLTytus** [comment]
It is not a bug, it is a April Fools' Day feature. The "GTA VI map" is forced whole April 1th but when switiching map using map selector (picture below) the previously loaded markers should be loaded again.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/6315826a-b368-48bd-a9b2-a4c251840c38)

**Comment by PLTytus** [comment]
Anyway I changed a code little bit, but mostly for next year. The fake map will forced just once.
