### ISSUE TITLE
route 68 gas station Screenshot

### ISSUE THREAD

**Issue by haasinc42** [PLTytus/GTAWeb#54]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
...
route 68 / dessert 

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
...
missing

**Your screenshot (best copy-paste it here):**
...
![route 68](https://github.com/PLTytus/GTAWeb/assets/160082047/f81c2c20-9c95-43a3-8e63-b3b27c82f7d3)

[68 gas station.zip](https://github.com/PLTytus/GTAWeb/files/14897068/68.gas.station.zip)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
...
horseshoecrab34

**Comment by PLTytus** [comment]
✅
