### ISSUE TITLE
Supplies Bunker drain to quick in both mode

### ISSUE THREAD

**Issue by hetisrobbert** [PLTytus/GTAWeb#55]
I have the Farmhouse Bunker with the Equipment and Staff upgrade. And I know it's now a 2 times sell week but I mention that the bunker supplies also last longer then 1h40m. It looks like 2 times (3h20m).

What i'm doing for now is using buy option again and set it directly to 100% so the timer will run again.

**Comment by PLTytus** [comment]
1. Did you checked both upgrades in settings?
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/3c7ab680-5caf-4832-b3d1-3b784c6dca8c) ![image](https://github.com/PLTytus/GTAWeb/assets/34415908/4f80ff8f-b2c5-4721-8046-f28e659d8f81)
2. How did you assigned your staff? Only product, only resarch, both? If both then moment when supplies are being decreased can be random - it is game issue.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/adb25515-e32c-4b03-b171-99a984209dac) ![image](https://github.com/PLTytus/GTAWeb/assets/34415908/ccc2929a-707c-4ffc-8cf6-418decbcf4c7)
3. Do you have GTA+? how did you set GTA+ button on toolkit? If it is green then time bonus for + members is taken, production time bonus affect supplies, it runs out faster.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/893ddf9b-14c1-4eb2-8368-ebd41d037e35) ![image](https://github.com/PLTytus/GTAWeb/assets/34415908/3bccfb3d-0253-4bbd-9615-4b83fefd2f86)

**Comment by hetisrobbert** [comment]
Bunker equipment is set to yes, staff is set to yes, but still the supplies wont last longer then 1h40m in the tool
I'm playing on PC so I didn't turn GTA+ on. The product and research bar are accurate, but when the supplies bar is empty and I go to the bunker still got around 50% of the supplies left.

**Comment by PLTytus** [comment]
I was anylizing decompiled code and leaked code (it has gunrunning functions with developer's comments 😅) and I just realized I was assuming that in both-mode supplies runs out faster, but it may actually runs out slower beacues both of the products are produced simultaneously but twice slower.
I updated the toolkit with new formula, let me know if now toolkit supplies bar meet the game one.

**Comment by hetisrobbert** [comment]
Thanks!

Because it was double money the last two days I was only using production. Now switched to both. I will let you know tomorrow!

Also the indication 1,5 and 2,0 etc. Doesn't look right on the site after changing to the new GTA week.
Bunker contract is indicating nothing and Bunker is showing 1,5 on second line and warehouse is showing 1,5 and 2,0.

![image](https://github.com/PLTytus/GTAWeb/assets/84876276/63b8df00-e4b9-468f-96b3-26e7114975d4)

**Comment by PLTytus** [comment]
> Bunker contract is indicating nothing

Because bonus ended, but the value should be 50k, 100k should be for mixed goods, the one below bunker - I'll look into this values.

> Bunker is showing 1,5 on second line

Yeah, because there is no money bonus, but there is time bonus for GTA+, and it is only for product, research have the default speed for them.


> warehouse is showing 1,5 and 2,0

2.0 cash for all, 1.5 speed for Lupe for GTA+

**Comment by PLTytus** [comment]
> the value should be 50k, 100k should be for mixed goods, the one below bunker - I'll look into this values

Added condition to detecte and correct this type of situation.

**Comment by hetisrobbert** [comment]
> Because bonus ended, but the value should be 50k, 100k should be for mixed goods, the one below bunker - I'll look into this values.
Ah oke, was thinking it should show 1,5 as normal my mistake!

> Yeah, because there is no money bonus, but there is time bonus for GTA+, and it is only for product, research have the default speed for them.
Ill understand!

> 2.0 cash for all, 1.5 speed for Lupe for GTA+
Clear to me all now. Thanks for the explain.

**Comment by hetisrobbert** [comment]
For now the speed is fine of draining supplies level bar. When using both. Tnx for all!
