### ISSUE TITLE
Arcade Safe

### ISSUE THREAD

**Issue by hetisrobbert** [PLTytus/GTAWeb#56]
The Arcade Safe says right away that there should be 5,000 in it every 48 minutes (day-game). But since I just started and so I am not full of game Arcades yet, the actual amount is now only 820 per hour approximately. Perhaps for this the tool could have some specify how many Arcades a person has. I only don't dare say if there is a fixed sum attached to this.

**Comment by PLTytus** [comment]
It is explained in help for toolkit:
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/5b9662e8-9a97-47ce-b200-be0e1aaaf42b)
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/1651a59c-8c4e-4de7-9c06-222dd00469df)
Just buy the cheapest arcade machine and put in on all slots.

**Comment by hetisrobbert** [comment]
Thanks for the explanation, I did go into that menu but then foolishly read over it. I didn't know this was random. I will take your tip with me!
