### ISSUE TITLE
Single mouse click count as multiple value clicks [TOUCHPAD]

### ISSUE THREAD

**Issue by hetisrobbert** [PLTytus/GTAWeb#57]
I don't know if I am the only one, but if I click once on the - or + to make a correction, quite often the tool counts this as multiple times so it then passes the value I want to set. + (plus) is then like 2, 3 or even 4 times up and - (minus) is just as much 2 till 3/4 down again. When I navigate with the keyboard (tab or shift+tab) and then press enter the toolkit does register this as one keystroke (mouse click). This is a little annoying if you want to set the vault or produced item one value higher or lower because you keep going past it

Further great compliments! For such great application

**Comment by PLTytus** [comment]
Fill up this (this is part of [issue template](https://github.com/PLTytus/GTAWeb/issues/new?assignees=&labels=issue&projects=&template=issue.md&title=) - please use the templates next time 😉) beacuse it might device/browser issue with the click-and-hold feature on these buttons which is useful when you need to change current value by more than 1-2 units.
I have no issue with changing value about 1 unit on newest desktop Chrome on Windows 10 and on mobile Safari on iOS 17.4.1.

```
- Device type [e.g. mobile, desktop]: 
- Device [e.g. iPhone 6, PC, MacBook]: 
- OS and its version [e.g. iOS 16.5, Windows 10 Home, Windows 11, ...]: 
- Browser and its version [e.g. chrome 114.0.5735.110]: 
```

**Comment by hetisrobbert** [comment]
I'm sorry! didn't see. And the template didn't show up at me directly. 

I'm using my laptop with Microsoft Windows 11 version 22H2 build 22621.3374 with Microsoft Edge Versie 123.0.2420.81 (Officiële build) (64-bits). Will try Chrome, and let you know! Didn't use that in a while. Since Edge is Chromium based.

**Comment by PLTytus** [comment]
Fixed.
