### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Malvum** [PLTytus/GTAWeb#61]
Hello, could you put the waiting time for cars at the tuning workshop and for motorcycles at MC?

**Comment by PLTytus** [comment]
I would like to this. Actually, I was planning it when I was working on Toolkit 2.0 but unfortunately it is random, so I am unable to do this. 

Tez2 described how it works [here](https://gtaforums.com/topic/974239-auto-shop-customer-repair-and-delivery-tips/?do=findComment&comment=1071757190). Works the same for motorcycles. Except the base timer is set to 30 minutes.

For current bonus week the chance is doubled, so given times are guaranteed to receive vehicle - but only this week.
