### ISSUE TITLE
Warehouses incorrectly display "Large Warehouse" for all sizes

### ISSUE THREAD

**Issue by awaymire** [PLTytus/GTAWeb#65]
**Basic info**
- Priority: low
- Subpage name: map
- Supbage URL: https://gtaweb.eu/gtao-map/
- Setted language: English
- Device type: Desktop
- Device: Macbook Air (also affects windows laptop, android phone)
- Mac Ventura 13.6.7 
- Browser and its version: chrome Version 125.0.6422.176 (Official Build) (arm64)

**Describe the issue (a clear and detailed description of the issue):**
The title of every warehouse is "Large Warehouse." The colors are coded correctly, as confirmed by hovering over each color of warehouse and viewing its capacity.

**To Reproduce  (detailed steps to reproduce the behavior):**
1. Click on any warehouse

**Expected behavior:**
I expect either the warehouse to simply be called "warehouse" and I can check the size, or for the size of the warehouse to be accurately reflected in the title (eg medium warehouse titled "medium warehouse" instead of "large warehouse"

**Screenshots or video:**
<img width="293" alt="Screenshot 2024-06-17 at 2 46 16 PM" src="https://github.com/PLTytus/GTAWeb/assets/16169347/b5a6fabb-80d5-4e13-83ad-f2b06b9d8e4a">
<img width="254" alt="Screenshot 2024-06-17 at 2 46 12 PM" src="https://github.com/PLTytus/GTAWeb/assets/16169347/2cee61a6-be70-43a9-ac17-9335dfc68f1d">
<img width="266" alt="Screenshot 2024-06-17 at 2 46 06 PM" src="https://github.com/PLTytus/GTAWeb/assets/16169347/6d01bf4a-e654-47a9-b14a-3769d3dfdf8f">

**Additional context (if you have somthing more to add):**
...

**Comment by PLTytus** [comment]
Fixed.
