### ISSUE TITLE
Acid package drop points for "home delivery" acid sell mission

### ISSUE THREAD

**Issue by Clayverlags** [PLTytus/GTAWeb#66]
**Describe your idea:**
In "home delivery" acid sell missions, player can directly drop acid package into blankets, and the bike is not necessary required to be around so the player can drive an Oppressor Mk2 instead. The drop points can be added for blind nevigation. 

**Examples (if you was inspired by some other website or project):**
As you still have to deliver them in order and cannot skip any one, the drop points can be marked with serial numbers.
Here is part of map made by Caihong.
[
![XM22_SELL_ACIDPACKAGE(by caihong)](https://github.com/PLTytus/GTAWeb/assets/115455502/24a98f4d-7674-4903-a92c-d339d37eeeed)
](url)

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
...

**Comment by PLTytus** [comment]
https://gtaweb.eu/gtao-map/ls/-/acid-lab-sell

- Added the rest of points for this mission and joined them with paths.
- Also roman numbers in corners for "stash" variant to put these locations in groups.
- The draggable area is now fixed for mobile devices - https://github.com/PLTytus/GTAWeb/issues/20

![image](https://github.com/user-attachments/assets/e5ecfb10-047a-4795-a1ad-0589f094c534)
