### ISSUE TITLE
Discount on Ammu-Nation

### ISSUE THREAD

**Issue by MateoUYmp3** [PLTytus/GTAWeb#67]
I suggest Add information about Ammu-Nation discounts. More specifically, if you complete a shooting gallery with a weapon, whether bronze, silver or gold, it gives you a small discount.

**Comment by PLTytus** [comment]
You talking about [this](https://gta.fandom.com/wiki/Ammu-Nation_Shooting_Ranges#Challenges)? It works also for multiplayer (GTA Online)? Ot is it only singleplayer feature? I am asking, because honestly I am hearing first time about this 😅

**Comment by MateoUYmp3** [comment]
At least all bronze medals awarded - all items are 10% off
At least all silver medals awarded: all items with a 15% discount
at me

**Comment by MateoUYmp3** [comment]
It is available in story mode only (I based it on the page you mentioned)

**Comment by PLTytus** [comment]
Ok, I will at this later. Priority at the moment is new content for GTA Online.

**Comment by PLTytus** [comment]
Added.
![image](https://github.com/user-attachments/assets/275b46ba-c690-46d3-a0e1-b11c49189c5c)
