### ISSUE TITLE
Limousine destinations

### ISSUE THREAD

**Issue by Antwelm** [PLTytus/GTAWeb#68]
The destinations the casino limousine can quck-jump to are only labelled by names. Should be in the map.

https://www.dexerto.com/gta/handy-gta-online-map-shows-all-casino-limousine-fast-travel-locations-1348571/

**Comment by PLTytus** [comment]
Good idea. I think I should also add other types of fast travel like CEO Helicopter, Taxi (I belive this one is on EE version only), Agency SUV - I didn't miss anything, right?

---

**TODO LIST:**
- [ ] casino limousine
- [ ] ceo helicopter
- [ ] agency limousine
- [ ] taxi

**Comment by PLTytus** [comment]
[https://gtaweb.eu/gtao-map/ls/-/fast-travel](Added) but without CEO Helicopter, because it only can teleport you to your warehouses and office, and it can spawn almost everywhere - so I do not see point in adding this one.

**Comment by Antwelm** [comment]
> Good idea. I think I should also add other types of fast travel like CEO Helicopter, Taxi (I belive this one is on EE version only), Agency SUV - I didn't miss anything, right?
> 
> **TODO LIST:**
> 
> * [x]  casino limousine
> * [ ]  ~ceo helicopter~
> * [x]  agency suv
> * [x]  taxi

Nicely done! Very good implementation! Spot on! Thanks!
