### ISSUE TITLE
Chinese Localization for Discount Text

### ISSUE THREAD

**Issue by Clayverlags** [PLTytus/GTAWeb#69]
**Describe your idea:**
In Chinese custom, discounts are usually written as "(1-X)折" instead of "X% off". Since it is reversed in Chinese, such localization will make it easier for Chinese speakers to understand the discount on the price.

**Rule of conversion:**
Usually, we only take two decimal digits, and ignore the second digit if it's 0.
E.g. I, a -10% is written as "九折", meaning that the sale price is 0.9 times of the original. In the phrase, "九" stands for 9, and "折" stands for a discount.
E.g. II, a -25% is written as "七五折", meaning that the sale price is 0.75 times of the original. "七" stands for 7, "五" stands for 5, and "折" stands for a discount.
If the case is -100%, a "免费" (free) should be used instead.
For Chinese characters (both Simplified and Traditional), 0-9 is:
`["零", "一", "二", "三", "四", "五", "六", "七", "八", "九"]`

**Example:**
Here is my realization:
```
let discount = 0.9; // a 90% off
const _NUM = ["零", "一", "二", "三", "四", "五", "六", "七", "八", "九"];
if(discount == 1){ // case where 100% off, free of charge
  return "免费"; // free
}else{
  discount = Math.round((1 - discount) * 100).toString(); //"10"
}
let discountText = "";
discountText += _NUM[discount[0]];
if(discount[1] != 0){
  discountText += _NUM[discount[1]];
}
discountText += "折";
return discountText; //"一折"
```

**Comment by PLTytus** [comment]
> E.g. I, a -10% is written as "九折", meaning that the sale price is 0.9 times of the original. In the phrase, "九" stands for 9, and "折" stands for a discount.

I am confused about this example. Is this mean, -10% and -91% will be both as 9? "九折"? How to write such high discounts - between 91 and 99% to not confuse them with 10, 20, 30, 40, 50, 60, 70, 80 and 90%? Is using 0 for -90% ("九零折") is incorrect?

Such high discounts are very unlikely but I think it is better to be prepared.

**Comment by Clayverlags** [comment]
Sorry for not making it clear. Let me explain it again.
 **"X折" means that the price is X/10 times of the original.**
If it is 25% off, it's in full written as "七点五折", meaning that it is 7.5/10 times the price. "点" stands for the decimal point (For Traditional Chinese, use "點"). **The decimal point is usually omitted** then it become "七五折".

> Is this mean, -10% and -91% will be both as 9? "九折"?
In case of -91%, which is 0.9/10 times of original price, **the first digit, which is 0, should be included**. So it is understandable to say it as "零九折". However, **In this case where first digit is 0, the decimal point cannot be omitted**. So it is"零点九折", (For Traditional Chinese, use "點", namely "零點九折").

> Is using 0 for -90% ("九零折") is incorrect?
Yes. Apparently there is no difference between 9/10 and 9.0/10 so it's not needed to show that 0 behind the hidden decimal point.

In addition. If you find it troublesome using Chinese numerals, you can instead: use Arabic numerals and not to omit the decimal point . E.g. "9 折" for -10%, "7.5 折" for -25% and "0.9 折" for -91%.

**Comment by PLTytus** [comment]
> In addition. If you find it troublesome using Chinese numerals, you can instead: use Arabic numerals and not to omit the decimal point . E.g. "9 折" for -10%, "7.5 折" for -25% and "0.9 折" for -91%.

If this form is correct, I am adding this version. It will be easier for me to debug and test when needed. It is also shorter, so it will work better in some cases.

<details>
<summary>Table with results for new function, from 0 to -100% discount.</summary>

| OTHERS | CHINESE |
| --- | --- |
| 0% | empty string |
| -1% | 9.9 折 |
| -2% | 9.8 折 |
| -3% | 9.7 折 |
| -4% | 9.6 折 |
| -5% | 9.5 折 |
| -6% | 9.4 折 |
| -7% | 9.3 折 |
| -8% | 9.2 折 |
| -9% | 9.1 折 |
| -10% | 9 折 |
| -11% | 8.9 折 |
| -12% | 8.8 折 |
| -13% | 8.7 折 |
| -14% | 8.6 折 |
| -15% | 8.5 折 |
| -16% | 8.4 折 |
| -17% | 8.3 折 |
| -18% | 8.2 折 |
| -19% | 8.1 折 |
| -20% | 8 折 |
| -21% | 7.9 折 |
| -22% | 7.8 折 |
| -23% | 7.7 折 |
| -24% | 7.6 折 |
| -25% | 7.5 折 |
| -26% | 7.4 折 |
| -27% | 7.3 折 |
| -28% | 7.2 折 |
| -29% | 7.1 折 |
| -30% | 7 折 |
| -31% | 6.9 折 |
| -32% | 6.8 折 |
| -33% | 6.7 折 |
| -34% | 6.6 折 |
| -35% | 6.5 折 |
| -36% | 6.4 折 |
| -37% | 6.3 折 |
| -38% | 6.2 折 |
| -39% | 6.1 折 |
| -40% | 6 折 |
| -41% | 5.9 折 |
| -42% | 5.8 折 |
| -43% | 5.7 折 |
| -44% | 5.6 折 |
| -45% | 5.5 折 |
| -46% | 5.4 折 |
| -47% | 5.3 折 |
| -48% | 5.2 折 |
| -49% | 5.1 折 |
| -50% | 5 折 |
| -51% | 4.9 折 |
| -52% | 4.8 折 |
| -53% | 4.7 折 |
| -54% | 4.6 折 |
| -55% | 4.5 折 |
| -56% | 4.4 折 |
| -57% | 4.3 折 |
| -58% | 4.2 折 |
| -59% | 4.1 折 |
| -60% | 4 折 |
| -61% | 3.9 折 |
| -62% | 3.8 折 |
| -63% | 3.7 折 |
| -64% | 3.6 折 |
| -65% | 3.5 折 |
| -66% | 3.4 折 |
| -67% | 3.3 折 |
| -68% | 3.2 折 |
| -69% | 3.1 折 |
| -70% | 3 折 |
| -71% | 2.9 折 |
| -72% | 2.8 折 |
| -73% | 2.7 折 |
| -74% | 2.6 折 |
| -75% | 2.5 折 |
| -76% | 2.4 折 |
| -77% | 2.3 折 |
| -78% | 2.2 折 |
| -79% | 2.1 折 |
| -80% | 2 折 |
| -81% | 1.9 折 |
| -82% | 1.8 折 |
| -83% | 1.7 折 |
| -84% | 1.6 折 |
| -85% | 1.5 折 |
| -86% | 1.4 折 |
| -87% | 1.3 折 |
| -88% | 1.2 折 |
| -89% | 1.1 折 |
| -90% | 1 折 |
| -91% | 0.9 折 |
| -92% | 0.8 折 |
| -93% | 0.7 折 |
| -94% | 0.6 折 |
| -95% | 0.5 折 |
| -96% | 0.4 折 |
| -97% | 0.3 折 |
| -98% | 0.2 折 |
| -99% | 0.1 折 |
| -100% | 免费 |
</details>
