### ISSUE TITLE
Acid lab sell mission markers and highlighting issue

### ISSUE THREAD

**Issue by misc2008** [PLTytus/GTAWeb#7]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: Low
- Subpage name: GTAO MAP
- Supbage URL: https://gtaweb.eu/gtao-map/ls/
- Setted language: English
- Device type: desktop
- Device: PC
- OS and its version: Windows 10 Home
- Browser and its version Firefox 114.0.2 (64-bit) / Also in Chrome 114.0.5735.135 (Official Build) (64-bit)

**Describe the issue (a clear and detailed description of the issue):**
...Police sting icons vanish when the green circle is placed over them. Also I cannot see the paperboy icons at all anywhere.

**To Reproduce  (detailed steps to reproduce the behavior):**
1. ...Enable Acid Lab Sell missions for display
2. ...locate a police sting icon outside the circle
3. ...move the circle to over the police sting icon

**Expected behavior  (how it should work):**
... Police string icons should not vanish

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
...

**Additional context (if you have somthing more to add):**
...

**Comment by PLTytus** [comment]
This is not issue, thats how it works. Police Sting is possible when Acid Lab is at least 1000m away from triggerpoint. The green area has 1000m radius.
