### ISSUE TITLE
cannot see all the dealers after todays update on site

### ISSUE THREAD

**Issue by vinaydeep26** [PLTytus/GTAWeb#72]
![image](https://github.com/user-attachments/assets/66e49c2f-cbed-46ad-8a0a-8244fcd09a54)
vinaydeep26

**Comment by PLTytus** [comment]
Fixed. There was also problem with Gun Van, Casino, LS Car Meet, Luxury Autos, Premium Deluxe Motorpsort and Vinewood Car Club.
