### ISSUE TITLE
Excess weapon parts and Mixed good timers

### ISSUE THREAD

**Issue by Sirish-PsiPhi** [PLTytus/GTAWeb#73]
Basic info
- Priority : Low
- Subpage name: Toolkit
- Supbage URL : https://gtaweb.eu/gtao-toolkit

Issue
The timers/production for both excess weapon parts(bunker) and mixed goods(office) sell missions are paused when the player status is set to offline. But as I have seen both of them do continue to produce their respective products even when the player is offline.

Expected behavior 
Timers/Production should continue to run even when player status is set to offline

**Comment by PLTytus** [comment]
I tested it, you're right. I will make appropriate changes.

**Comment by PLTytus** [comment]
Done.
