### ISSUE TITLE
GTAO Toolkit has incorrect information for car collections

### ISSUE THREAD

**Issue by cosmicspace** [PLTytus/GTAWeb#76]
**Basic info**
- Priority [in your opinion: High to Normal, depending on whether you're using the GTAO Toolkit
- Subpage name: GTAO Toolkit
- Supbage URL: https://gtaweb.eu/gtao-toolkit
- GTA+ [yes/no]: no
- Setted language: English, likely present in others
- Device type: desktop
- Device: PC
- OS and its version: Windows 11
- Browser and its version: Firefox 132.0.1 (64-bit)

**Describe the issue (a clear and detailed description of the issue):**
When you are using the GTAO Toolkit, the cars are a bit mixed up in terms of which screenshot applies to each collection and which cars are in each collection. A few are correct but most are not.

**To Reproduce  (detailed steps to reproduce the behavior):**
1. Open GTAO Toolkit
2. Use the Vehicle Cargo aspect of CEO Businesses, specifically Car Collections
3. Notice that the collections are not correct for the cars that are in them

**Expected behavior  (how it should work):**
The attached Excel file has the correct cars for each collection, and the screenshots present this information as well.

**Screenshots or video (if you can provided them,  a screenshot of the developer's console from when the problem occurred might be useful):**
[GTA Car Collections.xlsx](https://github.com/user-attachments/files/17657499/GTA.Car.Collections.xlsx)
![Car collection - End of Empires](https://github.com/user-attachments/assets/c3c86bf0-4980-4412-acf5-bf3305006d3a)
![Car collection - Fading Power](https://github.com/user-attachments/assets/606d757f-0813-41b8-b161-fce9a548b450)
![Car collection - Hip to be Square](https://github.com/user-attachments/assets/6be273a3-3e19-449c-b083-dfcf3b774e4d)
![Car collection - Molten Metal](https://github.com/user-attachments/assets/ab339457-b134-45a4-8da8-25342a27fda4)
![Car collection - No Direct Sunlight](https://github.com/user-attachments/assets/b5bcac5a-77cc-40ba-bb5c-6bfdc1503f24)
![Car collection - Pastel Perfection](https://github.com/user-attachments/assets/52145405-83ff-435c-a7bb-c91e40afeb88)
![Car collection - Shades of Blue](https://github.com/user-attachments/assets/a58d7933-548f-47c1-9892-14f852bbc1e1)
![Car collection - Stay Declasse](https://github.com/user-attachments/assets/5056898d-4c5e-4351-a44a-74070773e70e)
![Car collection - Uninsurable](https://github.com/user-attachments/assets/1a141108-6ea2-482b-b4a1-1c032b03bb97)
![Car collection - Birds of Paradise](https://github.com/user-attachments/assets/8067f2b2-f25f-419d-a4aa-27fbdfd5bb49)

**Additional context (if you have something more to add):**
Thank you for making this tool and the GTA maps in general. You're awesome!

**Comment by PLTytus** [comment]
You mean collection names are incorrectly assigned? I started checking if screenshots matches model and plate 😅

**Comment by PLTytus** [comment]
Fixed.

**Comment by cosmicspace** [comment]
I just did a refresh to check and everything looks good! Thanks!
