### ISSUE TITLE
Wrong location+SS of underwater perico chest

### ISSUE THREAD

**Issue by DragomRiderMax** [PLTytus/GTAWeb#77]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.
> 

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
https://gtaweb.eu/gtao-map/cp/-/treasure-chests/sm=17

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
Wrong location + wrong picture as the chest got moved to  a clearing nearby because OG spot was clipping
I already collected the chest today before  noticing the mistake, so i do not have it in my picture, sorry

**Your screenshot (best copy-paste it here):**
![CHEST](https://github.com/user-attachments/assets/caa5c1d0-b86c-4b17-aee1-e6ee2f56d2fe)

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
DragonRiderMax

**Comment by DragomRiderMax** [comment]
![CHESTA](https://github.com/user-attachments/assets/6a2bd49c-84be-4bdc-b300-0630784b2f53)
screenshot taken from YT video https://youtu.be/U2ZdnSsJkqY?si=n-ye9e6PMcm0VKYJ

**Comment by PLTytus** [comment]
Changed. Thanks.
