### ISSUE TITLE
perico merryweather weapon prep

### ISSUE THREAD

**Issue by DragomRiderMax** [PLTytus/GTAWeb#78]
**Describe your idea:**
On cayo perico weapon prep, there are three possible location the helicopter may take you to. I  found out that each heli spawn corresponds to each location as noted in screenshot below. Heli at the left (spot 1) will always go to Grapeseed. Heli in the middle (spot 2) will always go to the factory on the right. Heli on the right (spot 3) will always go to the spot near sandy shores airfield.

**Examples (if you was inspired by some other website or project):**
I discovered this on my own as I do this mission a lot

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**

![obrazek](https://github.com/user-attachments/assets/eb103cd0-2067-42e1-b501-5cdad39f39fa)

**Comment by PLTytus** [comment]
Changed. Thanks for this info.
