### ISSUE TITLE
Add additional cooldown timers

### ISSUE THREAD

**Issue by TheGreenkey** [PLTytus/GTAWeb#8]
**Describe your idea:**
Add additional cooldown timers like the Dax Fooligan missions.

I was looking for a website which lets me track various cooldowns for money making, which is where I found yours. (nice job btw!)
As a broke player I'm using every opportunity to make some extra cash and all of those missions like the Dax or CEO mixed goods missions are paying 50k for 5 minutes of work but they each have a different cooldown. It would be nice to be able to track those timers too.
The Yohan resupply missions for the nightclub might be another example of a timer to track (though those in particular only resupply your nightclub afaik).

**Examples:**
Dax
CEO Mixed Goods
Yohan
(some example missions)

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**

**Comment by PLTytus** [comment]
There was "Timers" feature in Toolkit 1.0. I am planning to bring it back to Toolkit 2.0.

**Comment by TheGreenkey** [comment]
That's awesome! Is there anyway one could help with development? I guess currently GTAWeb is closed source, will it always be?

**Comment by PLTytus** [comment]
Took a while 😅  but done.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/3e35bff7-cce3-4141-b0a2-ada7ac80b762)
