### ISSUE TITLE
All land SP pickups screenshots

### ISSUE THREAD

**Issue by DragomRiderMax** [PLTytus/GTAWeb#82]
> **NOTES:**
> Do not add any watermarks or your nickname on the screenshot - i will add it myself, just tell me below if you want it to be different from your name on GitHub.
> If you want to send multiple screenshots, you can upload a zip file (just use some known and safe hosting, best without file expiration) but list all the markers, the way I could quickly recognise which screenshot applies to which location.

PS: i did land only as water pickups are almost impossible to see. May revisit later, probably wont tho. Left out two health packs and one armor as those are inside FIB/IIA interiors and are unaccessible outside a few missions. If I ever revisit this, Ill submit those.

**Document link**
https://www.mediafire.com/file/awrxd9rm2c5el6r/gta_v_guns_land_COMPLETE.docx/file

**Location (use [share an individual marker feature](https://www.youtube.com/shorts/0wZY3bsB3GY) or take a screenshot of a map and mark the location on it):**
All markers are included below the pics

**What is wrong with current screenshot (e.g. missing, incorrect, outdated, my is better, etc.):**
missing
**Your screenshot (best copy-paste it here):**
in the document

**Author (to add your nickname on the screenshot, if you leave this empty, I will use your GitHub nickname):**
DragonRiderMax

**Comment by PLTytus** [comment]
Added. Huge thanks.
