### ISSUE TITLE
Exotic Exports

### ISSUE THREAD

**Issue by Bloodshot-Spider** [PLTytus/GTAWeb#9]
Similar to crossing of collectables such has the action figures or playing card, when using the map for all the potential spawn locations of exotic export. When you find one of these cars you would cross that car off and the location that it was crossed off would be darkened or uses the same visual effects has the other collectables. If that makes any sense

**Comment by PLTytus** [comment]
Crossing off feature for random events (Exotic Exports is kind of random event) is rather useless. When event - vehicle in this case - spawn at one point, next one can spawn at the very same point.

If you thinking about monitoring your progress for Exotic Exports, use list which is hidden inside tooltip. The list container current vehicles in proper order.
![image](https://github.com/PLTytus/GTAWeb/assets/34415908/fc21f4ca-4723-46eb-9aaf-9b9a632f7c17)
